version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gocontacts
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
      POSTGRES_PORT: 5000
    ports:
      - 5000:5000

  app:
    build: .
    command: ["./wait-for-it.sh", "db:5000", "--", "go", "run", "main.go"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db